# Generated by Django 3.1.4 on 2021-02-15 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20210215_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classlist',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.course', verbose_name='课程'),
        ),
    ]
