# Generated by Django 3.1.4 on 2021-02-16 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20210215_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='source',
            field=models.SmallIntegerField(choices=[(1, 'qq群'), (2, '内部转介绍'), (3, '官方网站'), (4, '百度推广'), (5, '抖音推广'), (6, '微博推广'), (7, '腾讯课堂'), (8, '网易公开课'), (9, '高校宣讲'), (10, '渠道代理'), (11, '其它')], default=1, verbose_name='客户来源'),
        ),
    ]
